[package]
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
description = "A fast file deduplicator. Replaces duplicate files with identical content with hardlinks."
repository = "https://github.com/pornel/duplicate-kriller"
documentation = "https://github.com/pornel/duplicate-kriller#readme"
name = "duplicate-kriller"
homepage = "https://github.com/pornel/duplicate-kriller"
keywords = ["dupe", "duplicate", "deduplication"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"
version = "1.1.0"

[[bin]]
name = "duplicate-kriller"
path = "src/bin.rs"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[dependencies]
getopts = "0.2.14"
sha1 = "0.2.0"

[dependencies.serde]
optional = true
version = "1.0"

[dependencies.serde_derive]
optional = true
version = "1.0"

[dependencies.serde_json]
optional = true
version = "1.0"

[dev-dependencies]
file = "1.1.1"
tempdir = "0.3.5"

[features]
default = ["json"]
json = ["serde", "serde_derive", "serde_json"]
