[package]
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
description = "A fast file deduplicator. Replaces duplicate files with identical content with hardlinks."
repository = "https://github.com/pornel/duplicate-kriller"
documentation = "https://github.com/pornel/duplicate-kriller#readme"
name = "duplicate-kriller"
version = "0.9.2"
keywords = ["dupe", "duplicate", "deduplication"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[dependencies]
sha1 = "0.2.0"

[dev-dependencies]
tempdir = "0.3.5"
